// File: web/tests/hash-chain.test.ts
// Client-side hash-chain verification: valid chains verify green; tampering, relinking, and
// sequence gaps are flagged at the exact record.
import { describe, expect, it } from 'vitest';
import {
  GENESIS_HASH,
  canonicalJson,
  recordHash,
  verifyBatch,
  verifyChain,
  parseJsonl,
  type ChainAnchors,
} from '@/lib/hash-chain';
import type { Hex, TraceRecord } from '@/lib/types';

function makeChain(n: number): TraceRecord[] {
  const records: TraceRecord[] = [];
  let prev: Hex = GENESIS_HASH;
  for (let seq = 0; seq < n; seq++) {
    const body = {
      agentId: 'agent-1',
      seq,
      prevHash: prev,
      ts: `2026-09-20T00:00:0${seq}Z`,
      kind: 'inference' as const,
      response: { text: `thought ${seq}` },
    };
    const hash = recordHash(body);
    records.push({ ...body, hash });
    prev = hash;
  }
  return records;
}

describe('hash chain', () => {
  it('canonical JSON sorts keys recursively and drops undefined', () => {
    expect(canonicalJson({ b: 1, a: { d: 2, c: 3 }, z: undefined })).toBe('{"a":{"c":3,"d":2},"b":1}');
  });

  it('matches the backend hash exactly (cross-implementation parity vector)', () => {
    // Vector generated by backend/src/crypto/hashchain.ts computeRecordHash —
    // sha256(prevHashBytes(32) || utf8(canonicalJSON(body))). If this fails,
    // one side drifted from the shared contract.
    const body = {
      agentId: 'a',
      seq: 0,
      prevHash: GENESIS_HASH,
      ts: '2026-09-20T00:00:00.000Z',
      kind: 'decision' as const,
      detail: { summary: 'parity' },
    };
    expect(recordHash(body as unknown as Omit<TraceRecord, 'hash'>)).toBe(
      '0x8af6d12275d8105698db8420f28ae85206324eb8e0929bc8d36a105cfd5bce47',
    );
  });

  it('verifies a well-formed chain', () => {
    expect(verifyChain(makeChain(5), GENESIS_HASH)).toEqual({ ok: true, count: 5 });
  });

  it('flags a tampered record at its seq', () => {
    const chain = makeChain(5);
    const r2 = chain[2]!;
    chain[2] = { ...r2, response: { text: 'FORGED' } };
    const result = verifyChain(chain, GENESIS_HASH);
    expect(result).toEqual({ ok: false, brokenAtSeq: 2, reason: 'hash-mismatch' });
  });

  it('flags a broken link', () => {
    const chain = makeChain(4);
    const r3 = chain[3]!;
    const relinked = { ...r3, prevHash: GENESIS_HASH };
    chain[3] = { ...relinked, hash: recordHash(relinked) };
    const result = verifyChain(chain, GENESIS_HASH);
    expect(result).toEqual({ ok: false, brokenAtSeq: 3, reason: 'link-mismatch' });
  });

  it('flags a missing record as a seq gap', () => {
    const chain = makeChain(5);
    chain.splice(2, 1);
    const result = verifyChain(chain, GENESIS_HASH);
    expect(result).toMatchObject({ ok: false, reason: 'seq-gap' });
  });

  it('parses JSONL including blank lines', () => {
    const chain = makeChain(2);
    const jsonl = chain.map((r) => JSON.stringify(r)).join('\n') + '\n\n';
    expect(parseJsonl(jsonl)).toHaveLength(2);
  });
});

describe('anchored batch verification', () => {
  it('a batch starting at seq 0 anchors at the genesis hash', () => {
    const anchors: ChainAnchors = new Map();
    const result = verifyBatch(makeChain(3), 0, anchors);
    expect(result).toEqual({ ok: true, count: 3, anchored: 'genesis' });
  });

  it('threads expectedPrev across batches — later batches stay genesis-anchored', () => {
    const chain = makeChain(6);
    const anchors: ChainAnchors = new Map();
    expect(verifyBatch(chain.slice(0, 3), 0, anchors)).toEqual({ ok: true, count: 3, anchored: 'genesis' });
    expect(verifyBatch(chain.slice(3, 6), 3, anchors)).toEqual({ ok: true, count: 3, anchored: 'genesis' });
  });

  it('a mid-chain batch with no prior anchor verifies as slice only', () => {
    const chain = makeChain(6);
    const anchors: ChainAnchors = new Map();
    expect(verifyBatch(chain.slice(3, 6), 3, anchors)).toEqual({ ok: true, count: 3, anchored: 'slice' });
  });

  it('a batch after a slice-anchored batch remains slice-anchored', () => {
    const chain = makeChain(6);
    const anchors: ChainAnchors = new Map();
    verifyBatch(chain.slice(2, 4), 2, anchors);
    expect(verifyBatch(chain.slice(4, 6), 4, anchors)).toEqual({ ok: true, count: 2, anchored: 'slice' });
  });

  it('flags a batch whose first record does not link to the previous batch', () => {
    const chain = makeChain(6);
    const anchors: ChainAnchors = new Map();
    verifyBatch(chain.slice(0, 3), 0, anchors);
    const r3 = chain[3]!;
    const relinked = { ...r3, prevHash: GENESIS_HASH };
    const forged = [{ ...relinked, hash: recordHash(relinked) }, ...chain.slice(4, 6)];
    const result = verifyBatch(forged, 3, anchors);
    expect(result).toMatchObject({ ok: false, brokenAtSeq: 3, reason: 'link-mismatch' });
  });

  it('a failed batch does not record an anchor for the next batch', () => {
    const chain = makeChain(4);
    const anchors: ChainAnchors = new Map();
    const r1 = chain[1]!;
    const tampered = [chain[0]!, { ...r1, response: { text: 'FORGED' } }];
    expect(verifyBatch(tampered, 0, anchors).ok).toBe(false);
    expect(anchors.size).toBe(0);
  });
});

