// File: web/eslint.config.mjs
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next and not ours to lint.
    ignores: ['node_modules/**', '.next/**', 'playwright-report/**', 'test-results/**', 'next-env.d.ts'],
  },
];

export default config;
